apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrp-runner-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nrp-runner-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nrp-runner-pods
subjects:
- kind: ServiceAccount
  name: nrp-runner-manager
roleRef:
  kind: Role
  name: nrp-runner-pods # this must match the name of the Role you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nrp-runner-deployment
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nrp-runner-deployment
subjects:
- kind: ServiceAccount
  name: nrp-runner-manager
roleRef:
  kind: Role
  name: nrp-runner-deployment # this must match the name of the Role you wish to bind to
  apiGroup: rbac.authorization.k8s.io

