apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-state
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
